spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_aap
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted

email:
  email-host: smtp.163.com
  transport-type: smtp
  from-user: massd2002
  from-email: massd2002@163.com
  auth-code: 2368018

kb-qa-interface-prefix: http://localhost:7861