spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_aap
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

kb_qa_interface_prefix: http://localhost/8000